name: DEV Test Build

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: 拉取仓库
        uses: actions/checkout@v4

      - name: 获取版本
        shell: powershell
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV

      - name: 安装Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13.1

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install imageio
          pip install -r requirements.txt

      - name: 编译
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          show-memory: true
          onefile-tempdir-spec: "%TEMP%\\onekey_%PID%_%TIME%"
          windows-icon-from-ico: icon.jpg
          company-name: "ikunshare"
          product-name: "Onekey"
          include-data-dir: |
            ./web/templates=web/templates
            ./web/static=web/static
          file-version: ${{ env.PACKAGE_VERSION }}
          product-version: ${{ env.PACKAGE_VERSION }}
          file-description: "Onekey Depot Manifest Downloader."
          copyright: "Copyright © 2025 ikunshare All Rights Reserved."
          output-file: Onekey_v${{ env.PACKAGE_VERSION }}.exe
          assume-yes-for-downloads: true
          output-dir: build

      - name: 上传包
        uses: actions/upload-artifact@v4
        with:
          name: Onekey_v${{ env.PACKAGE_VERSION }}.exe
          path: build/Onekey_v${{ env.PACKAGE_VERSION }}.exe
